# Render deployment configuration for Better Day Energy - Unified Modular Service

services:
  # Unified LOI Automation System with Modular Architecture
  - type: web
    name: loi-automation-system
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python unified_modular_server.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: loi-postgres
          property: connectionString
      - key: PORT
        value: 8002
      - key: ENVIRONMENT
        value: production
      - key: LACRM_API_TOKEN
        value: "14d1b7eb88cc6b51e75a6b00b2b6e41c"
      - key: LACRM_API_BASE
        value: "https://api.lessannoyingcrm.com"

databases:
  # PostgreSQL Database for signatures and CRM cache
  - name: loi-postgres
    databaseName: loi_automation
    user: loi_user
    plan: starter