# Render deployment configuration for LOI Automation System

services:
  # LOI Automation System with integrated signature service
  - type: web
    name: loi-automation-system
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_main.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: loi-postgres
          property: connectionString
      - key: PORT
        value: 8002
      - key: ENVIRONMENT
        value: production

databases:
  # PostgreSQL Database for signatures and CRM cache
  - name: loi-postgres
    databaseName: loi_automation
    user: loi_user
    plan: starter