# Render deployment configuration for LOI Automation System

services:
  # Main LOI API Service
  - type: web
    name: loi-automation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: loi-postgres
          property: connectionString
      - key: CRM_API_KEY
        sync: false # Set in Render dashboard
      - key: SMTP_USERNAME
        value: transaction.coordinator.agent@gmail.com
      - key: SMTP_PASSWORD
        sync: false # Set in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
    
  # Signature Service (DocuSign-like interface)
  - type: web
    name: loi-signature-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python signature_server_production.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: loi-postgres
          property: connectionString
      - key: SIGNATURE_SECRET_KEY
        generateValue: true
      - key: API_BASE_URL
        value: https://loi-automation-api.onrender.com
      - key: ALLOWED_ORIGINS
        value: https://loi-signature-service.onrender.com
      - key: SSL_REDIRECT
        value: true

databases:
  # PostgreSQL Database
  - name: loi-postgres
    databaseName: loi_automation
    user: loi_user
    plan: starter # Upgrade to standard for production

# Static site for any frontend components
staticSites:
  - type: web
    name: loi-dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff